layout_spectrum: 0.3184747
color:
  saturation: 0.2432868
  brandStrength: 0.4562202
  lightness: 0.6664876
  rhythmicContrast: 0.9081632
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.5580022
name: w0rd
